dist: trusty
language: rust

os:
  - linux

rust:
  - nightly

jobs:
  include:
  - os: osx
    osx_image: xcode11.3
    rust: nightly
  - os: linux
    rust: nightly
    env: FEATURES="encryption,jemalloc,portable,sse"

env:
  global:
  - RUST_BACKTRACE=1

cache: false

before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy

script:
  # copile rocksdb may cost more than 10 minutes, see https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
  - travis_wait make clippy
  - cargo fmt --all -- --check
  - cargo build --features=$FEATURES
  - cargo test --all --features=$FEATURES
