[package]
name = "librocksdb_sys"
version = "0.1.0"
authors = ["Jay Lee <busyjaylee@gmail.com>"]
build = "build.rs"
links = "rocksdb"

[dependencies]
libc = "0.2.11"
libtitan_sys = { path = "libtitan_sys" }

[dev-dependencies]
tempfile = "3.1"

[features]
default = []
jemalloc = ["jemalloc-sys"]
# portable doesn't require static link, though it's meaningless
# when not using with static-link right now in this crate.
portable = ["libtitan_sys/portable"]
sse = ["libtitan_sys/sse"]

[build-dependencies]
cc = "1.0.3"
cmake = "0.1"

[dependencies.jemalloc-sys]
version = "0.1.8"
optional = true
features = ["unprefixed_malloc_on_supported_platforms"]

[dependencies.libz-sys]
version = "1.0.25"
features = ["static"]

[dependencies.bzip2-sys]
git = "https://github.com/alexcrichton/bzip2-rs.git"

[dependencies.lz4-sys]
git = "https://github.com/busyjay/lz4-rs.git"
branch = "adjust-build"

[dependencies.zstd-sys]
git = "https://github.com/gyscos/zstd-rs.git"

[dependencies.snappy-sys]
git = "https://github.com/busyjay/rust-snappy.git"
branch = "static-link"
