[package]
name = "rocksdb-sys"
version = "0.3.0"
authors = ["Arkadiy Paronyan arkadiy@ethcore.io>"]
license = "MIT/Apache-2.0/BSD"
description = "Native bindings to librocksdb"
readme = "README.md"
repository = "https://github.com/paritytech/rust-rocksdb.git"
keywords = ["ffi", "rocksdb"]

build = "build.rs"
links = "rocksdb"

[features]
default = [ "static" ]
static = []

[dependencies]
libc = "0.2"
local-encoding = "0.2.0"
snappy-sys = { git = "https://github.com/paritytech/rust-snappy" }

[build-dependencies]
cmake = "0.1"
